### ISSUE TITLE
[Todo] 2/23

### ISSUE THREAD

**Issue by hyochan** [dooboolab/hackatalk-server#54]
- [x] Migration for tests as shared in gallery resolver - @dooboolab
- [x] Support relay style pagination as described in [link](https://facebook.github.io/relay/graphql/connections.htm) - @geoseong 
   - [Reference](https://github.com/reindexio/react-native-graphql-workshop/blob/master/docs/04-Adding-pagination.md)
   - Continue Mar 8th.
- [x] Implement `singleUpload` resolver by - @YongPilMoon 
   - Related #33 
   - Continue Mar 8th.
- [x] Implement `Reaction` model & schema & resolver - @daadaadaah
   - [x] Emoji test in client
- [x] Research Virgil Security on rotate key - @seonghyeonkimm 
- [ ] Readme update - @godon019 
- [x] Sequelize migration medium - @smallbee3
   - Support for `Reaction` model.
- [ ] Support localization through the context - @Bang9 @jeontaeyun
- ~~Service layer refactoring~~

**Comment by hyochan** [comment]
@godon019 I hope you can follow up on the `readme` enhancement with `PR` and `ISSUE` templates.
